# Saving and sharing your NumPy arrays

In [3]:
import numpy as np

## Create your arrays

Now that you have imprted the NumPy library, you can make a couple of arraysl let's start with two 1D arrays, `x` and `y`, where `y = x**2`. you will assign `x` to the integers from 0 to 9 using `np.arange`.

In [ ]:
x = np.arange(0, 10, 1)
y = x ** 2
print(x)
print(y)

## Save your arrays with NumPy's `savez`

The first thing you will do is save them to a file as zipped arrays using `savez`. You will use two options to label the arrys in the file,

1. `x_axis = x`: the option is assigning the name `x_axis` to the variable `x`
2. `y_axis = y`: the option is assigning the name `y_axis` to the variable `y`

In [4]:
np.savez("x_y_squared.npz", x_axis=x, y_axis=y)

## Remove the saved arrays and load them back with NumPy's `load`

1. remove `x` and `y` from the workspace widh `del`
2. load the arrarys into the workspace in a dictionary with `np.load`

To see what variables are in the workspace, use the Jupyter/IPython "magic" command `whos`.

In [1]:
del x, y

NameError: name 'x' is not defined

In [6]:
load_xy = np.load("x_y_squared.npz")
print(load_xy.files)

['x_axis', 'y_axis']


In [4]:
%whos

Variable   Type      Data/Info
------------------------------
np         module    <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>


## Reassign the NpzFile arrays to `x` and `y`

In [8]:
x = load_xy["x_axis"]
y = load_xy["y_axis"]
print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]


## Another option: saving to human-readable csv 

You use the `savetxt` to save `x` and `y` in comma separated value file, `x_y_squared.csv`. The resulting csv is composed if ASCII characters. You can load the file back into NumPy or read it with other programs.

## Rearrange the data into a single 2D array

First, you have to create a single 2D array from your two 1D arrays. The csv-filetype is a spreadsheet-style dataset. The csv arranges numbers in rows-separated by new lines-and columns-separated by commas. You use two NumPy functions to format the data:

1. `np.block`: this function appends arrays together into a 2D array
2. `np.newaxis`: this function forces the 1D array into a 2D column vector with 10 rows and 1 column.

In [9]:
array_out = np.block([x[:, np.newaxis], y[:, np.newaxis]])
print("the output array has shape ", array_out.shape, "with values: ")
print(array_out)

the output array has shape  (10, 2) with values: 
[[ 0  0]
 [ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]
 [ 5 25]
 [ 6 36]
 [ 7 49]
 [ 8 64]
 [ 9 81]]


## Save the data to csv file using `savetxt`

You use `savetxt` with a three options to make your file easier to read:

- `X = array_out`: this option thells `savetxt` to save your 2D array, `array_out`, to the file `x_y_squared.csv`
- `header = 'x, y'`L this option writes a header before any daa that labels the columns of the csv
- `delimter = ','`: this option tells `savetxt` to place a comma between each column in the file

In [10]:
np.savetxt("x_y_squared.csv", X=array_out, header="x, y", delimiter=",")

## Load CSV

In [14]:
del x, y

NameError: name 'x' is not defined

In [17]:
load_xy = np.loadtxt("x_y_squared.csv", delimiter=",")

In [18]:
load_xy.shape

(10, 2)

In [19]:
x = load_xy[:, 0]
y = load_xy[:, 1]
print(x)
print(y)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]


## Success, but remeber your types

When you saved the arrays to the csv file, you did not preserve the `int` type. When loading the arrays back into your workspace the default process will be to load the csv file as a 2D floating point array e.g `load_xy.dtype == 'float64'` and `load_xy.shape == (10, 2)`.